Feat: Adapt gp_relsizes_stats for Cloudberry

diff --git a/.github/workflows/build-cloudberry.yml b/.github/workflows/build-cloudberry.yml
--- a/.github/workflows/build-cloudberry.yml
+++ b/.github/workflows/build-cloudberry.yml
@@ -275,6 +275,11 @@ jobs:
                "make_configs":["gpcontrib/gp_stats_collector:installcheck"],
                "extension":"gp_stats_collector"
               },
+              {"test":"gpcontrib-gp-relsizes-stats",
+               "make_configs":["gpcontrib/gp_relsizes_stats:installcheck"],
+               "extension":"gp_relsizes_stats",
+               "shared_preload_libraries":"gp_relsizes_stats"
+              },
               {"test":"ic-expandshrink",
                "make_configs":["src/test/isolation2:installcheck-expandshrink"]
               },
@@ -1456,6 +1461,20 @@ jobs:
                     psql postgres"
                 then
                     echo "Error creating gp_stats_collector extension"
+                    exit 1
+                fi
+                ;;
+              gp_relsizes_stats)
+                if ! su - gpadmin -c "source ${BUILD_DESTINATION}/cloudberry-env.sh && \
+                  source ${SRC_DIR}/gpAux/gpdemo/gpdemo-env.sh && \
+                  gpconfig -c shared_preload_libraries -v 'gp_relsizes_stats' && \
+                  gpstop -ra && \
+                  echo 'CREATE EXTENSION IF NOT EXISTS gp_relsizes_stats; \
+                        SHOW shared_preload_libraries; \
+                        TABLE pg_extension;' | \
+                    psql postgres"
+                then
+                    echo "Error creating gp_relsizes_stats extension"
                     exit 1
                 fi
                 ;;
